name: uzdst2
description: UZDst second algorithm implementation in Dart
version: 0.0.1
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  ffi: 2.1.2
  convert: 3.1.1
  pointycastle: 
    git:
      url: https://github.com/ishifr/pc-dart
      ref: 96146f3f573a3898e2c66ddb1254f6bc48bf92aa

dev_dependencies:
  lints: 3.0.0
  test: 1.24.0
